image: node:latest
# To use Remote Caching, uncomment the next lines and follow the steps below.
variables:
   TURBO_TOKEN: $TURBO_TOKEN
   TURBO_TEAM: $TURBO_TEAM
stages:
  - build
build:
  stage: build
  before_script:
    - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@6.32.2
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install
    - pnpm build
    - pnpm test
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .pnpm-store